### ISSUE TITLE
Stuff

### ISSUE THREAD

**Issue by ghost** [copiga/tempsense#1]
Hi Josh,

Can you explain brieflly in leymans terms what the stuff does? Im currently writing up the documentation for all of this. Unsure what is happening in the house keeping files, cleanerer, the tiva c stuff,status commands, etc.

Also ive requested for the Python file you put on google drive to be here so all the links look similar in the documentation.

Thanks,

Lee

**Comment by copiga** [comment]
the housekeeping and cleanerer are from when we left eclipse and went to make+gcc, this left us with many less needed files and means we dont need to get the binaries hosted

each filename reflects what is done in the file,
    led.c and led.h have functions for dealing with the LED
    adc.c and adc.h are for using the ADC so we can get temperature
    main.c and main.h contain the main function and others not used anywhere else
    master_commands.c and master_commands.h are for dealing with input from the raspberry pi

this is not the place for the python. python is your end, create your own repo and put that there. this repo is for the embedded side and the python will run on the raspi

**Comment by ghost** [comment]
Hi Josh!

Thanks for the the specific information :)
I've updated updated it on the file and uploaded it to the Google Drive, so
please take a look and let me know if anything needs changing. I've also
created a Repository for the higher level stuff and put a link on the
Protocol file.

The Google Drive has been also cleaned up so people actually know where
stuff is too.

Cya soon!

Lee

**Comment by copiga** [comment]
cool
