### ISSUE TITLE
effector functions dont do anything

### ISSUE THREAD

**Issue by copiga** [copiga/tempsense#4]
decide on a GPIO to use for external heater control and programme it in. initialise the GPIO in main.c:bootUp() and use it in effector.c:outputOn() and effector.c:outputOff() when the output argument is 0.

bonus points for renaming the output argument to outputID

**Comment by copiga** [comment]
i would suggest testing with an LED

**Comment by Kilahn** [comment]
Added a basic GPIO output on pin PD7. OutputOn sends 1, OutputOff sends 0.

**Comment by copiga** [comment]
now moved to PA2
